relecture fiche
InseeFrLab/utilitR pull request #186
Opened 2020-12-14 12:33 UTC by CTassart

J'ai apporté quelques légères modifications.
_- ligne 25 :_  
j'ai renommé `Comment **créer** un service Rstudio sur le SSP Cloud`en `Comment **travailler avec** un service Rstudio sur le SSP Cloud` car la partie **création** est l'un des paragraphes de cette partie.
_- ligne 44 :_
Ajout d'une image pour représenter le petit dossier d'accès au catalogue `datascience`.
_- ligne 79 :_
modification du lien pour afficher la bonne image,
_- Ligne 118 :_
je propose de remplacer le `XXXX` (et l'image correspondante) par `lgaliana` ?

Je fais quelques propositions d'ajout à la fiche pour qu'elle ait une portée un peu plus large et touche des agents qui ne **git** pas encore.  
_- ligne 88 :_
    - j'ai ajouté un paragraphe `Sauvegarder son travail` qui aborde la fonction d'`export` de RStudio.  
    - j'ai inséré les liens vers les images correspondantes.
_- ligne 145 :_
je verrai bien un encadré, en fin de partie `Utiliser S3 avec un service Rstudio` , qui aborderait la façon de `uploader` ses fichiers manuellement dans `minio` et comment gérer les liens.

2020-12-14 13:23 UTC, oliviermeslin requested changes
Une correction de mise en forme, et une question de fond.

2020-12-14 13:23 UTC, oliviermeslin commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +L'immense majorité des problèmes rencontrés à la création d'un compte SSP Cloud découle d'un `username` ne respectant pas ces règles. Si cela vous arrive malgré tout, veuillez mettre un message sur l
::: {.remarque data-latex=""}
La grande majorité des problèmes rencontrés à la création d'un compte SSP Cloud découle d'un `username` ne respectant pas ces règles. Dans ce cas, la seule solution consiste à demander aux administrateurs du SSP Cloud de supprimer votre compte, pour que vous puissiez en créer un nouveau. Vous pouvez contacter les administrateurs en écrivant un message sur le salon Tchap `SSPCloud` (https://www.tchap.gouv.fr/#/room/#SSPCloudXDpAw6v:agent.finances.tchap.gouv.fr).
:::

2020-12-14 13:23 UTC, oliviermeslin commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +### Sauvegarder son travail
Je ne sais si nous voulons recommander cet usage, qui me semble un peu trop artisanal. Il me semble que le SSP Cloud est un environnement performant, mais qui demande aux agents de s'investir pour bien maîtriser les outils, et je trouve que cette façon de sauvegarder ses travaux n'est pas dans l'esprit de la plate-forme.

Qu'en pensez-vous: @CTassart, @pierre-lamarche, @linogaliana, @RLesur ?

2020-12-16 10:10 UTC, linogaliana commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +### Sauvegarder son travail
Oui je suis d'accord avec @oliviermeslin car l'intégration avec git est très bien faite sur le SSP cloud. Il n'y a pas besoin de connaître les rudiments de Git pour en faire grâce à Rstudio

2020-12-16 11:09 UTC, RLesur requested changes

2020-12-16 11:09 UTC, RLesur commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
>  - L'**option `Enable IP protection`** (dans l'onglet `Networking`) est une option de sécurité informatique très contraignante, qui est activée par défaut. Il est conseillé de la désactiver, en partic
```suggestion
```
Ce n'est pas une bonne idée de laisser tourner un service pendant plusieurs jours, ils doivent être temporaires.
A la limite, on pourrait écrire qu'il faut désactiver cette protection lorsqu'on sait qu'on va devoir accéder à l'environnement RStudio depuis des addresses IP différentes.

2020-12-16 11:09 UTC, RLesur commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +### Sauvegarder son travail
Entièrement d'accord : il ne faut parler que de git. Les autres options vont contre le principe même de la reproductibilité. Or le projet utilitR promet des pratiques reproductibles.

2020-12-16 11:09 UTC, RLesur commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
>  * *stockage des codes*: il est nécessaire d'utiliser une plate-forme de développement pour stocker des programmes informatiques, tel que [Gitlab](www.gitlab.com) ou [Github](www.github.com). L'usage
```suggestion
* *stockage des codes*: il est nécessaire d'utiliser une plate-forme de développement pour stocker des programmes informatiques, tel que [Gitlab](www.gitlab.com) ou [Github](www.github.com).
```
Le gitlab interne n'est pas accessible depuis le SSP Cloud

2020-12-16 11:09 UTC, RLesur commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
>  * *stockage des données*:  la plateforme SSP Cloud propose un système de stockage de données nommé S3. Depuis votre service Rstudio, vous pourrez facilement accéder à des données stockées sur S3 grâc
J'ai un projet de démo ici si ça vous intéresse https://github.com/RLesur/sspcloud-demo

2020-12-20 19:43 UTC, oliviermeslin commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
>  * *stockage des données*:  la plateforme SSP Cloud propose un système de stockage de données nommé S3. Depuis votre service Rstudio, vous pourrez facilement accéder à des données stockées sur S3 grâc
@RLesur: j'avais loupé ce commentaire. Oui, clairement on va le reprendre. Pourrais-tu passer cette démonstration sur un compte officiel Insee (InseeFrLab)? Dès que tu le fais l'intègre à la fiche.

2021-01-05 07:51 UTC, oliviermeslin approved these changes

2021-01-05 07:56 UTC, oliviermeslin commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
>  * *stockage des données*:  la plateforme SSP Cloud propose un système de stockage de données nommé S3. Depuis votre service Rstudio, vous pourrez facilement accéder à des données stockées sur S3 grâc
C'est fait.

2021-01-05 07:58 UTC, merged