Fiche utiliser r insee [WIP]
InseeFrLab/utilitR pull request #201
Opened 2021-01-19 15:20 UTC by acazaubiel

La première version de la fiche sur la personnalisation de R à l'Insee, conformément à l'issue #199 .

Feel free to add anything, c'est ma première PR ever.

2021-01-25 16:50 UTC, linogaliana commented on _bookdown.yml
> +  - 01_R_Insee/Travail_avec_R_Insee.Rmd
Je me suis trompé en réglant le conflit dans ce fichier, c'est cette fiche la bonne
```suggestion
  - 01_R_Insee/Fiche-personnaliser-R.Rmd
```

2021-01-26 14:25 UTC, acazaubiel commented
J'ai encore des choses à faire ? Ou c'est approximativement good ?

2021-01-26 14:51 UTC, linogaliana approved these changes
Je trouve la fiche très bien. Mes remarques sont principalement des suggestions formelles que tu peux accepter en cliquant

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +La personnalisation de R, ou de RStudio doit être réalisée avec précaution, car personnaliser son environnement de travail, c'est prendre le risque de perdre la reproductibilité de ses travaux.
```suggestion
La personnalisation de `R`, ou de `RStudio` doit être réalisée avec précaution, car personnaliser son environnement de travail, c'est prendre le risque de rendre moins reproductible ses travaux.

```

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Ne personnalisez pas R, sauf dans des cas très précis :
```suggestion
Ne personnalisez pas `R`, sauf dans des cas très précis :

```

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +* pour modifier des paramètres qui n'ont pas vocation à être bien configurés dans R à l'Insee, comme le proxy ou des chemins vers executables ;
```suggestion
* pour modifier des paramètres qui n'ont pas vocation à être bien configurés dans `R` à l'Insee, comme le proxy ou des chemins vers executables ;

```

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +* pour changer des éléments qui n'ont aucun impact sur les calculs, mais peuvent vous faciliter la vie, comme l'augmentation de la taille de l'historique, le repos, le prompt, etc.
> pour changer des éléments qui n'ont aucun impact sur les calculs, mais peuvent vous faciliter la vie, comme l'augmentation de la taille de l'historique, le repos, le prompt, etc.

Qu'est-ce que tu entends par repos ? L'adresse des dépôts de package type miroir du CRAN ?

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +R a été conçu, dès le début, pour permettre une très grande flexibilité d'utilisation. Cette flexibilité engendre toutefois une complexité dans ses procédures d'initialisation.  La documentation sur
```suggestion
`R` a été conçu, dès le début, pour permettre une très grande flexibilité d'utilisation. Cette flexibilité engendre toutefois une complexité dans ses procédures d'initialisation.  [La documentation sur le lancement de `R`](https://cran.r-project.org/web/packages/startup/vignettes/startup-intro.html) montre d'ailleurs toute la complexité de la chose :

```

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +3. R prépare la session, avec les informations récupérées précédemment, mais également d'autres, comme par exemple les données qu'il aurait pu conserver dans un .Rdata, puis il charge les packages de
```suggestion
3. R prépare la session, avec les informations récupérées précédemment, mais également d'autres, comme par exemple les données qu'il aurait pu conserver dans un `.Rdata`, puis il charge les packages de base, avant par exemple de charger l'historique des commandes (s'il existe). C'est grâce à ce dernier temps que R recharge les données et l'historique après s'être interrompu inopunément.

```

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Sans complexifier outre mesure, sachez que les deux premiers temps se décomposent eux-mêmes en deux sous-temps : il est possible de définir des fichiers *environment* ou *profile* plus génériques que
Il faut expliquer le système en poupée russe des .Renviron et .Rprofile: dans la racine de R > dans un projet Rstudio

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +3. Relancez R, via *Session/Restart* ou *Ctrl+Shift+F10*
>  3. Relancez R, via *Session/Restart* ou *Ctrl+Shift+F10* 

@oliviermeslin : tu pourras formatter les touches comme tu l'as fait à d'autres endroits?

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Lorsqu'il teste un vecteur de booléen, R se contente de tester la première valeur, et met un simple avertissement. Toutefois, avec la modification de `.Renviron` de type `_R_CHECK_LENGTH_1_CONDITION_
```suggestion
Lorsqu'il teste un vecteur de booléen, R se contente de tester la première valeur, et met un simple avertissement. Toutefois, avec la modification de `.Renviron` de type `_R_CHECK_LENGTH_1_CONDITION_ = "TRUE"`, il est possible de modifier ce comportement et de générer une erreur (qui stoppera le code), si on fournit à R un vecteur au lieu de fournir un simple scalaire. Le code précédent... n'imprimera donc rien du tout et s’arrêtera avec une erreur chez vous ! Chez un autre utilisateur, il n'y aura pas d'erreur. Vous comprenez mieux les raisons pour lesquels modifier l'environnement peut conduire à des résultats non reproductibles ! 

```

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +La navigation sur Internet depuis un poste de l'Insee est contrôlée par un *proxy* qu'il faut paramétrer pour accéder à Internet.
```suggestion
La navigation sur Internet depuis un poste de l'Insee, comme dans de nombreuses institutions, est contrôlée par un *proxy* (intermédiaire entre le *web* et un ordinateur) qu'il faut paramétrer pour accéder à Internet.

```

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Un fichier `.Rprofile` pourrait typiquement ressembler à quelque chose comme :
Tu peux faire un lien avec le .Rprofile du livre: impression d'un message pour les contributeurs

(il y a des fonctions, c'est pas très propre, mais à terme mais on va les mettre dans un package spécifique #218)

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Pour voir certaines options aisément modifiables, la fonction `options()` affiche les valeurs actuellement chargées, et il est possible de les modifier à la volée via `options(nom_de_l_option=valeur_
Il me semble qu'`options` ne survit pas à une session `R`. Ca vaut le coup de préciser la nuance

2021-01-26 14:51 UTC, linogaliana commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Les autres opérations modifiant le comportement de base (comme `stringAsFactors=FALSE`) doivent être partagées et accessibles.
Préciser : plus besoin de faire ça dans R 4.0 car c'est devenu le comportement par défaut

2021-01-26 14:58 UTC, linogaliana commented
> 
> 
> J'ai encore des choses à faire ? Ou c'est approximativement good ?

@acazaubiel je t'ai fait quelques retours. Tu peux les valider en clique-bouton

2021-01-26 19:35 UTC, acazaubiel commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +* pour changer des éléments qui n'ont aucun impact sur les calculs, mais peuvent vous faciliter la vie, comme l'augmentation de la taille de l'historique, le repos, le prompt, etc.
Oui, exactement, l'adresse des dépots de packages.

2021-01-26 19:42 UTC, acazaubiel commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Ne personnalisez pas R, sauf dans des cas très précis :
A titre très personnel, je trouve que cette typographie de R (dans tout le bouquin) dans le style informatique rend la lecture plus compliquée. On sait que R est un logiciel statistique, pas besoin de le mettre en valeur (idem pour RStudio). 
Mais je comprends également votre position, et cette fiche sera harmonisée avec les autres 😸

2021-01-27 10:23 UTC, oliviermeslin requested changes
J'ai fait déjà un paquet de modifications. Je vais continuer.

2021-01-27 10:23 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +* il **contient une ligne vide finale** : cette ligne vide est indispensable, ne l'oubliez jamais !
```suggestion
* il modifie les paramètres du _proxy_ pour permettre à `R` de se connecter à Internet ;
* il modifie des variables internes à `R` (telles que `_R_CHECK_LENGTH_1_CONDITION_`  et `_R_CHECK_LENGTH_1_LOGIC2_`) ;
* il **contient une ligne vide finale** : cette ligne vide est indispensable, ne l'oubliez jamais !

```

2021-01-27 10:23 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +3. Relancez R, via *Session/Restart* ou *Ctrl+Shift+F10*
```suggestion
La méthode la plus simple pour modifier le fichier `.Renviron` est la suivante :

1. Ouvrir le fichier `.Renviron`. La commande `usethis::edit_r_environ()` permet d'ouvrir le fichier `.Renviron` de votre profil utilisateur (c'est le fichier d'environnement utilisé lorsqu'il n'y a pas de fichier d'environnement à votre projet). Si vous travaillez dans un `RProject`, la commande `usethis::edit_r_environ(scope="project")` permet d'ouvrir le le fichier `.Renviron` spécifique à votre projet.
2. Modifier le fichier, sans oublier la ligne vide en fin de document. 
3. Sauvegarder le fichier.
3. Relancez `R`, via `Session > Restart R` ou <kbd>Ctrl</kbd> + <kbd>⇧ Shift</kbd> + <kbd>F10</kbd>.
```

2021-01-27 15:57 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +```
```suggestion
Il faut être prudent lorsqu'on modifie des variables internes à `R`, car ces modifications peuvent aboutir à ce que les résultats des scripts ne soient pas reproductibles. Par exemple, `R` a un comportement assez étrange dans le cas suivant : 
```{r}
vecteurboolean <- c(TRUE, FALSE, NULL)
if (vecteurboolean) {
  cat("Je suis vrai ! \n")
} else {
  cat("Je suis faux ! \n")
}
```

```

2021-01-27 16:23 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +
```suggestion
Lorsqu'une condition porte sur un vecteur de booléens (`TRUE` ou `FALSE`), `R` utilise uniquement le premier élément du vecteur pour vérifier si condition est remplie, et renvoie un simple avertissement à l'utilisateur. Toutefois, il est possible de modifier ce comportement par défaut en indiquant `_R_CHECK_LENGTH_1_CONDITION_ = "TRUE"` dans le fichier `.Renviron` : `R` renverra alors une erreur et stoppera le code si `R` doit vérifier une condition sur un vecteur au lieu d'un simple scalaire. Dans ce cas, le code précédent ne renverra rien du tout et s’arrêtera avec une erreur. En revanche, chez un autre utilisateur dont le fichier `.Renviron` ne contient pas ce réglage, il n'y aura pas d'erreur. Le même code aboutit donc à des résultats différents en raison de différences dans les variables d'environnement.
```

2021-01-27 16:34 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +:::
```suggestion
Il est possible de modifier les paramètres de son environnement ou d'en générer d'autres après l'ouverture de la session `R`, avec la commande `Sys.setenv()`. Vous pouvez par exemple exécuter la commande `Sys.setenv("MON_API_INSEE"="jamais")`. De même la fonction `Sys.getenv()` permet de lister certaines valeurs présentes dans l'environnement actuel. Toutefois, toutes les procédures d'initialisation de R se seront déjà déroulées alors avec les anciennes valeurs, définies par défaut. Cette subtilité peut être importante !

::: {.remarque data-latex=""}
Comme dans de nombreuses institutions, la navigation sur Internet depuis un poste de l'Insee est contrôlée par un *proxy* (intermédiaire entre le *web* et un ordinateur). Il est indispensable de paramétrer l'adresse du _proxy_ pour que `R` puisse accéder à Internet (par exemple pour télécharger un _package_). Pour ce faire, vous pouvez récupérer l'adresse du _proxy_ interne en exécutant la commande suivante :
```{r, eval=FALSE}
curl::ie_get_proxy_for_url()
```
Puis vous pouvez ajouter l'adresse du _proxy_ dans votre fichier `.Renviron`. Il faut ajouter deux lignes dans ce fichier :
```{r, eval = FALSE}
http_proxy=adresse_du_proxy
https_proxy=adresse_du_proxy
```
:::

```

2021-01-27 16:35 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +### .Rprofile
```suggestion
### Le fichier `.Rprofile`

```

2021-01-27 16:39 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Un fichier `.Rprofile` pourrait typiquement ressembler à quelque chose comme :
```suggestion
Le fichier `.RProfile` contient du code `R` qui sera exécuté par `R` après le chargement des fichiers `.Renviron`. Voici trois utilisations standards du fichier `.Rprofile` :

* modifier le miroir par défaut du CRAN (pour télécharger des _packages_) ;
* modifier le message d'accueil de la session ;
* personnaliser l'affichage de `R`.

Un fichier `.Rprofile` peut par exemple ressembler à ceci :

```

2021-01-27 16:46 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Un exemple plus réaliste de `.Rprofile` peut être trouvé [ici](https://github.com/InseeFrLab/utilitR/blob/master/.Rprofile) : c'est le fichier qui permet notamment de réaliser la documentation d'Util
```suggestion
Ce fichier `.Rprofile` permet de :

* définir un miroir par défaut pour le CRAN ;
* modifier l'affichage de l'invite de commande (le ">" de début de ligne devient "R> ") ;
* modifier l'affichage par défaut des nombres décimaux  ;
* modifier l'affichage de la console lorsqu'une partie du code reste à écrire (le "+ " en début de ligne devient "+++ ") ;
* dans le cadre d'un appel à la console, la largeur des impressions est fixée à 120 ;
* les fonctions `.First` et `.Last` permettent d'effectuer des opérations spécifiques au lancement et à la fermeture de la session R (imprimer du texte dans le cas présent) ;
* Attention, comme précédemment, **un fichier `.Rprofile` doit se terminer par une ligne vierge**.

La fonction `options()` affiche les valeurs actuellement chargées pour les options. Il est possible de les modifier à la volée avec la commande `options(nom_de_l_option=valeur_de_l_option)`. Attention toutefois, modifier une option avec la fonction `options()` n'est valable que pour la session de `R` actuellement active ! Si `R` redémarre, toutes les options modifiées à la volée ne sont plus prises en compte. Si vous voulez modifier durablement la valeur d'une option, il est préférable de modifier le fichier `.Rprofile`.

Un exemple plus réaliste de `.Rprofile` peut être trouvé [ici](https://github.com/InseeFrLab/utilitR/blob/master/.Rprofile) : c'est le fichier qui permet notamment de réaliser la documentation d'`utilitR`. Notez notamment le message à l'ouverture du projet ! Avoir des fonctions n'est pas forcément interdit, tant que ces fonctions sont également partagées, comme c'est le cas dans ce projet !

```

2021-01-27 16:48 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +
```suggestion
::: {.conseil data-latex=""}

Si vous définissez des réglages spécifiques dans votre `.Rprofile`, il est fortement conseillé de :

* travailler dans le `.Rprofile` d'un projet, et non pas le `.Rprofile` général de votre profil d'utilisateur ;
* partager le fichier `.Rprofile` du projet, après avoir vérifié qu'il ne contenait aucune information sensible.

**Il est fortement déconseillé de réaliser les choses suivantes dans le fichier `.Rprofile`**:

* charger des _packages_ ;
* définir des alias de fonctions ;
* modifier le comportement par défaut de `R`, comme par exemple `options(stringAsFactors=FALSE)`.

En effet, toute personne qui ne dispose pas de ce fichier de configuration ne sera pas en mesure de reproduire vos travaux.
:::
```

2021-01-27 16:58 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +* [R for Enterprise: Understanding R’s Startup, by Sean Lopp (RStudio)](https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/)
```suggestion
## Pour en savoir plus

L'immense majorité de la documentation sur l'utilisation des fichiers de configuration de `R` est en langue anglaise : 

* [Using `.Rprofile` and .`Renviron`](https://github.com/numbats/resources/blob/b2fdc170277ecebea9a6358d7d222b55a206d70e/rprofile-renviron.Rmd) par Nicholas Tierney ;
* [R Startup](https://rstats.wtf/r-startup.html), chapitre 7 de _Rstats - What they forgot to teach you_, par Jennifer Bryan er Jim Hester ;
* [Managing `R` with `.Rprofile`, `.Renviron`, `Rprofile.site`, `Renviron.site`, `rsession.conf`, and `repos.conf`](https://support.rstudio.com/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf) par Alex Gold ;
* [Efficient `R` Programing - chapter 2.5](https://csgillespie.github.io/efficientR/set-up.html#r-startup) par Colin Gillespie \& Robin Lovelace ;
* [`R` for Enterprise: Understanding R’s Startup](https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/) par Sean Lopp (RStudio).
```

2021-01-27 17:05 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Les autres opérations modifiant le comportement de base (comme `stringAsFactors=FALSE`) doivent être partagées et accessibles.
```suggestion
**La personnalisation de `R` est une opération sensible qui ne doit pas interférer avec l'exigence de reproductibilité des travaux statistiques.** Cette personnalisation doit donc porter uniquement sur des modifications sans impact sur les calculs et sur des informations ayant vocation à ne pas être diffusées. Ces informations à ne pas diffuser peuvent être de deux types :

* **informations sensibles** (comme les identifiants d'API ou les paramètres de proxy). Il est important que ces informations ne figurent pas dans les programmes de façon à pouvoir partager librement les codes ;
* **informations d'infrastructure** (comme les chemins vers des exécutables). Ces informations n'ont pas vocation à être partagées, car elles varient d'un poste d'un agent à l'autre.

Les autres opérations modifiant le comportement de base (comme `stringAsFactors=FALSE`) doivent être partagées et accessibles, _via_ le fichier `.Rprofile`.
```

2021-01-27 17:07 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +## Quelques bonnes pratiques
Deux points:

- Je me demande si la partie bonnes pratiques ne devrait pas être en premier, juste après la recommandation.
- Je me demande si on ne devrait pas donner une règle précise sur le partage des fichiers de config, par exemple: ne __jamais__ partager le `.Renviron`, et partager le `.Rprofile` uniquement lorsque c'est celui d'un projet (le `.Rprofile` du profil utilisateur c'est pas important). Ca pourrait même être dans les recommandations. @linogaliana : un avis?

2021-02-04 14:02 UTC, acazaubiel commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +## Quelques bonnes pratiques
Mouais, mais la structure des fiches est telle que normalement, on conclut par cette partie...

2021-02-04 14:17 UTC, acazaubiel commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +Comme vous pouvez le constater, un tel fichier n'est pas constitué de code R, mais de paires **nom=valeur**. Chaque paire définit une variable d'environnement qui sera exploitée par R pour interagir
résolu manuellement, j'avais oublié de cliquer sur cette suggestion de commit.

2021-02-04 14:19 UTC, acazaubiel commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +* il définit sa clé d'API dans une variable MON_API_INSEE . Ultérieurement le code pourra faire appel à cette variable via `Sys.getenv("MON_API_INSEE")`. Ce faisant la clé confidentielle n'est pas di
idem, résolution manuelle.

2021-02-04 19:11 UTC, oliviermeslin commented on 01_R_Insee/Fiche-personnaliser-R.Rmd
> +## Quelques bonnes pratiques
OK

2021-02-05 10:51 UTC, merged