Ajout section programmer tidyverse (modifs @acazaubiel dans #232)
InseeFrLab/utilitR pull request #306
Opened 2021-05-05 17:37 UTC by linogaliana

close #232 #228

2021-05-05 17:38 UTC, linogaliana commented
@acazaubiel suite à https://github.com/InseeFrLab/utilitR/pull/232#issuecomment-832871275, tu peux vérifier que j'ai pas oublié un élément de ta PR (#232)

2021-05-06 06:24 UTC, oliviermeslin requested changes

2021-05-06 06:24 UTC, oliviermeslin commented on 03_Fiches_thematiques/Fiche_tidyverse.Rmd
> +               colonne = REG) # fonctionne !
```suggestion
selectionner_colonne <- function(donnees,colonne) {
  retour <- donnees %>%
    select({{colonne}})
  
  return(retour)
}

# Cette fois, le code fonctionne!
selectionner_colonne(donnees=head(bpe_ens_2018),
               colonne = REG)
```

2021-05-06 06:24 UTC, oliviermeslin commented on 03_Fiches_thematiques/Fiche_tidyverse.Rmd
> +
```suggestion
Pour réussir à créer des fonctions facilement compatibles avec le `tidyverse`, il faut faire appel à un opérateur spécifique, appelé *curly-curly* ou *doublestache* : `{{ }}`. Il s'agit de l'équivalent `tidyverse` de la fonction `get` présentée dans le chapitre [Manipuler ses données avec data.table](#datatable). Son utilisation est particulièrement simple, car il suffit d'entourer la variable par ces accolades.

```

2021-05-06 06:24 UTC, oliviermeslin commented on 03_Fiches_thematiques/Fiche_tidyverse.Rmd
> +:::
```suggestion
::: {.remarque}

Il peut arriver que vous trouviez sur internet une page recommandant l'usage de l'expression `eval(parse())`. Il est fortement conseillé de ne _jamais_ l'utiliser pour les raisons suivantes :

* elle est susceptible de créer des problèmes de sécurité. Tout le contenu à l'intérieur du `parse` est interprété par `R` comme du code à lancer, _quel que soit le contenu_. Il est donc particulièrement sensible aux problèmes d'[injection de code](https://fr.wikipedia.org/wiki/Injection_de_code_dans_les_applications_web) ;
* sa performance est très mauvaise ;
* l'identification des *bug* est particulièrement délicate, avec des messages d'erreurs peu opportuns et compliqués à comprendre.

:::
```

2021-05-06 06:24 UTC, oliviermeslin commented on 03_Fiches_thematiques/Fiche_tidyverse.Rmd
> +:::
Je déplace

```suggestion
```

2021-05-06 06:24 UTC, oliviermeslin commented on 03_Fiches_thematiques/Fiche_tidyverse.Rmd
> +
```suggestion

::: {.remarque}

L'opérateur `:=` du `tidyverse` ne remplit pas les mêmes fonctions que l'opérateur `:=` présenté dans la fiche [Manipuler ses données avec data.table](datatable): 

* Dans `data.table`, l'opérateur sert à créer une nouvelle variable en limitant le coût en mémoire de cette opération ;
* Dans le `tidyverse`, l'opérateur sert à faire comprendre à `dplyr` que la partie à gauche est un nom de colonne à ré-interpréter sans les guillemets
:::
```

2021-05-06 06:24 UTC, oliviermeslin commented on 03_Fiches_thematiques/Fiche_tidyverse.Rmd
> +               nouveau_nom = "region") # fonctionne !
```suggestion
selectionner_et_renommer <- function(donnees,colonne, nouveau_nom = "nouveau_nom") {
  retour <- donnees %>%
    select({{colonne}}) %>%
    rename({{nouveau_nom}}:={{colonne}})
  
  return(retour)
}

# Ce code fonctionne!
selectionner_et_renommer(
  donnees=head(bpe_ens_2018),
  colonne = REG,
  nouveau_nom = "region")
```

2021-05-06 06:24 UTC, oliviermeslin commented on 03_Fiches_thematiques/Fiche_tidyverse.Rmd
> +::: {.conseil data-latex=""}
C'est _vintage_ comme grammaire!

```suggestion
::: conseil
```

2021-05-06 06:24 UTC, oliviermeslin commented on 03_Fiches_thematiques/Fiche_tidyverse.Rmd
> +Pour fonctionnariser un code utilisant le `tidyverse`, il est recommandé :
```suggestion
Pour fonctionnaliser un code utilisant le `tidyverse`, il est recommandé :
```

2021-05-06 06:24 UTC, oliviermeslin commented on 03_Fiches_thematiques/Fiche_tidyverse.Rmd
> +Si les exemples précédents se basent tous sur `dplyr`, il est à remarquer que les solutions présentées s'appliquent à toute la philosophie du *tidyverse*, y-compris `ggplot2` (_c.f._ [Faire des graph
```suggestion
Si les exemples précédents se basent tous sur `dplyr`, il est à remarquer que les solutions présentées s'appliquent à tous les _packages_ du `tidyverse`, y compris `ggplot2` (_c.f._ [Faire des graphiques avec `ggplot2`](#ggplot2)).
```

2021-05-06 06:29 UTC, oliviermeslin commented
Merci @acazaubiel, cette section est top ! Voici de premières remarques. Je referai un second tour après.

2021-05-17 08:56 UTC, acazaubiel commented
Hello, les modifications me conviennent, mais comme je ne suis plus l'auteur, impossible pour moi d'accepter les commits... :(

2021-05-17 09:07 UTC, oliviermeslin approved these changes

2021-05-17 13:50 UTC, merged