Fiche SSPCloud
InseeFrLab/utilitR pull request #315
Opened 2021-05-10 14:49 UTC by linogaliana

Complément à #193

Co-authored-by: Cédric Tassart <cedric.tassart@insee.fr>
Co-authored-by: Meslin Olivier <K2KFED@ad.insee.intra>
Co-authored-by: lgaliana <lino.galiana@insee.fr>
Co-authored-by: Lino Galiana <linogaliana@yahoo.fr>
Co-authored-by: Romain Lesur <RLesur@users.noreply.github.com>
Co-authored-by: Lino Galiana <33896139+linogaliana@users.noreply.github.com>

**Compléter une description indicative ici.**

Si la modification est associée à une *issue*, elle peut être identifiée par son numéro, par exemple `#10`.

Pour fermer automatiquement une *issue* lorsque la `pull request` sera validée, marquer

```markdown
`close #XX`
```

en remplaçant  `#XX` par le numéro de l'*issue* (par exemple `#10`)

## Checklist:

En faisant cette *pull request*, je confirme que :

- [ ] J'ai lu le [guide des contributeurs](CONTRIBUTING.md)
- [ ] Ma proposition respecte les canons formels de la documentation `utilitR`
- [ ] Les exemples de code `R` ont été testés sur ma machine
- [ ] J'ai testé, sur ma machine, que la documentation compile avec mes ajouts (`bookdown::render_book("index.Rmd", output_dir = "_public", output_format = "utilitr::bs4_utilitr")`
produit un résultat
- [ ] Si j'y suis invité (cela ne fonctionne pas pour toutes les `pull requests`), je consulte le site de prévisualisation `https://www.${BRANCH_NAME}--preview-docr.netlify.app/`

2021-05-19 09:27 UTC, RLesur requested changes
Principalement une remarque sur le username

2021-05-19 10:13 UTC, MelineeTS commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +```{r lancer-rstudio, echo = FALSE, fig.cap= "Lancer un service RStudio", out.width = "100%"}
Je n'ai pas la même image, https://datalab.sspcloud.fr/my-lab/catalogue/inseefrlab-helm-charts-datascience/rstudio/deploiement
J'ai forcement accés à la config

2021-05-19 10:14 UTC, MelineeTS commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +utilitr::include_image("./pics/SSPCloud/02_lancer_rstudio.png")
Vous avez deux fois la même image, c'est normal ?

2021-05-19 10:16 UTC, MelineeTS commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +```{r, echo = FALSE, fig.cap= "Liste des services ouverts", out.width = "100%"}
Pouvez vous ajouter un message appelant à éteindre ses services ?

Liste des services ouverts. N'oubliez pas d'éteindre régulièrement les services que vous n'utilisez pas pour ne pas gaspiller de ressource.
#BercyVert ;)

2021-05-19 11:08 UTC, MelineeTS commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +utilitr::include_image("./pics/SSPCloud/04_exemple_service.png", ratio_compression = 1)
ça c'est ce qu'on a après avoir cliqué sur la clé plate. Il faut ajouter cette étape

2021-05-19 16:09 UTC, linogaliana commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +```{r, echo = FALSE, fig.cap= "Liste des services ouverts", out.width = "100%"}
Le message est passé dans 5664ea81f9e65f57e678662b26feb73f83c35f84 🌲 🐼 🐨

2021-05-19 16:29 UTC, linogaliana commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +utilitr::include_image("./pics/SSPCloud/04_exemple_service.png", ratio_compression = 1)
done (0907bf84e957e5df9b557c8800882f37441ceda8)

2021-05-19 16:29 UTC, linogaliana commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +utilitr::include_image("./pics/SSPCloud/02_lancer_rstudio.png")
non, c'est corrigé (61dafcd2915036575ef4977db542c7a5c9dd44c8)

2021-05-19 16:33 UTC, linogaliana commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +```{r lancer-rstudio, echo = FALSE, fig.cap= "Lancer un service RStudio", out.width = "100%"}
J'ai repris des captures d'écran que Marc m'a envoyé. Je pense qu'avec ces captures, on est en avance sur l'UI actuelle

2021-05-20 09:02 UTC, linogaliana commented on 01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
> +```{r lancer-rstudio, echo = FALSE, fig.cap= "Lancer un service RStudio", out.width = "100%"}
J'ai la confirmation de Marc, c'est bien la future interface (déployée dans quelques jours). Je vais laisser cette image, on aura pas à refaire la capture quand ce sera déployé

2021-05-20 09:11 UTC, linogaliana commented
> 
> 
> Principalement une remarque sur le username

@RLesur j'ai modifié la remarque en conséquence. Ok pour toi ?

2021-05-20 09:32 UTC, merged